//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Stagaires__Al_Omrane_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_StagairesEntities : DbContext
    {
        public Gestion_StagairesEntities()
            : base("name=Gestion_StagairesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateur { get; set; }
        public virtual DbSet<Etablissements> Etablissements { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Responsables> Responsables { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Spécialité> Spécialité { get; set; }
        public virtual DbSet<Villes> Villes { get; set; }
        public virtual DbSet<Stagaires> Stagaires { get; set; }
    }
}
