//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Stagaires__Al_Omrane_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profiles()
        {
            this.Stagaires = new HashSet<Stagaires>();
        }
        public int Id_P { get; set; }
        public string Libelle { get; set; }
        public string CV { get; set; }
        public string Experience { get; set; }
        public string Compétence { get; set; }
        public string ProjetRealisé { get; set; }
        public Nullable<int> Spés { get; set; }
    
        public virtual Spécialité Spécialité { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stagaires> Stagaires { get; set; }
    }
}
